language: python

jobs:
  include:
    - os: linux
      python: 3.7
      env: TOXENV=py37
    - os: linux
      python: 3.8
      env: TOXENV=py38

install:
  - pip3 install -r requirements-dev.txt

script: make test

notifications:
  email:
    on_success: never
