language: python

jobs:
  include:
    - os: linux
      python: 3.7
      env: TOXENV=py37
    - os: linux
      python: 3.8
      env: TOXENV=py38
    - os: osx
      osx_image: xcode9.4
      language: generic
      env: PYENV_VERSION=3.7-dev TOXENV=py37
    - os: osx
      osx_image: xcode11
      language: generic
      env: PYENV_VERSION=3.8-dev TOXENV=py38

install:
  - pip install tox

script: tox

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then  bash <(curl -s https://codecov.io/bash); fi

notifications:
  email:
    on_success: never
