language: python

jobs:
  include:
    - os: linux
      python: 3.7
      env: TOXENV=py37
    - os: linux
      python: 3.8
      env: TOXENV=py38
    - os: osx
      language: shell
      env: TOXENV=py37
    - os: osx
      language: shell
      env: TOXENV=py38

install:
  - pip3 install tox

script: python3 -m tox

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
