# language: python

# python:
#   - "3.7"
#   - "3.8"

# install:
#   - pip install -r requirements-dev.txt

# script:
#   - make test

# after_success:
#   - bash <(curl -s https://codecov.io/bash) -f coverage_out.info.cleaned

language: python

jobs:
  include:
    - os: linux
      python: 3.7
      env: TOXENV=py37
    - os: linux
      python: 3.8
      env: TOXENV=py38

install:
  - pip install -r requirements-dev.txt

script: make test

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage_out.info.cleaned