language: python

python:
  - "3.7"
sudo: false
# command to install dependencies
install:
  - pip install -r requirements-dev.txt

# command to run tests
script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage_out.info.cleaned || echo "Codecov did not collect coverage reports"
