language: python

jobs:
  include:
    - os: linux
      python: 3.7
      env: TOXENV=py37
    - os: linux
      python: 3.8
      env: TOXENV=py38
    - os: osx
      osx_image: xcode9.4
      language: generic
      env: TOXENV=py37
    - os: osx
      osx_image: xcode11
      language: generic
      env: TOXENV=py38

install:
  - pip3 install tox

script: python3 -m tox

notifications:
  email:
    on_success: never
