language: python

jobs:
  include:
    - os: linux
      python: 3.7
      env: TOXENV=py37
    - os: linux
      python: 3.8
      env: TOXENV=py38
    - os: osx
      language: generic
      env: TOXENV=py37
    - os: osx
      language: generic
      env: TOXENV=py38

install:
  - pip install tox

script: tox

notifications:
  email:
    on_success: never
