language: python

jobs:
  include:
    - os: linux
      python: 3.7
      env: TOXENV=py37
    - os: linux
      python: 3.8
      env: TOXENV=py38
    - os: osx
      python: 3.7
      env: TOXENV=py37
    - os: osx
      python: 3.8
      env: TOXENV=py38

install:
  - pip install tox

script: tox

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then python -m codecov ; fi

notifications:
  email:
    on_success: never
