image:
  - Visual Studio 2019

environment:
  matrix:
  - TOXENV: py37
  - TOXENV: py38

build: off

install:
  - choco install make
  - C:\Python38-x64\python.exe -m pip install -r requirements-dev.txt

test_script:
  - C:\Python38-x64\python.exe -m pytest
