name: CI

on: [push]

jobs:
  build-windows:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: install
      run: |
        pip install -r requirements-dev.txt
    - name: test
      run: |
        make test